export const INCREMENT_WINDOW_SIZE = "INCREMENT_WINDOW_SIZE";
export const DECREMENT_WINDOW_SIZE = "DECREMENT_WINDOW_SIZE";
export const TOGGLE_DOMAIN         = "TOGGLE_DOMAIN";
export const SET_SELECTED_ITEM     = "SET_SELECTED_ITEM";
export const SET_HOVERED_YEAR      = "SET_HOVERED_YEAR";
