version: 2
jobs:
  build:
    docker:
      - image: circleci/node:dubnium
    working_directory: ~/repo
    context: org-global
    steps:
      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          - v2-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - run:
          command: |
            sudo apt-get clean
            sudo apt-get update
            sudo apt install rsync
            echo $HOST
            echo $USER
            rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress ./build/ $USER@$HOST:~/my_site --delete
